const arr = [
  {
    title: "Egg",
    price: 40,
    id: 111,
    category: "Popular",
    description:
      "Whether you're already consuming sustainable meats like grass-fed beef, or you're heading in that direction, it's important to understand that meat raised on grass cannot always be prepared in the same way as conventional meat. Grass-fed beef is much leaner so there is little to insulate it from the heat source, making it important to cook with lower temperatures. Also because of the lack of insulation, the meat will cook about 30-50% faster! ",
    rating: 5,
    reviews: 25,
    availablity: "In Stock",
    img: "https://i.ibb.co/0s2RkBk/images-4.jpg",
  },
  {
    title: "Corn",
    price: 40,
    id: 112,
    category: "Popular",
    description:
      "Whether you're already consuming sustainable meats like grass-fed beef, or you're heading in that direction, it's important to understand that meat raised on grass cannot always be prepared in the same way as conventional meat. Grass-fed beef is much leaner so there is little to insulate it from the heat source, making it important to cook with lower temperatures. Also because of the lack of insulation, the meat will cook about 30-50% faster! ",
    rating: 4,
    reviews: 15,
    availablity: "In Stock",
    img: "https://i.ibb.co/c2W9Qb7/images-2.jpg",
  },
  {
    title: "Fish and Chicken",
    price: 50,
    id: 113,
    category: "Popular",
    description:
      "Whether you're already consuming sustainable meats like grass-fed beef, or you're heading in that direction, it's important to understand that meat raised on grass cannot always be prepared in the same way as conventional meat. Grass-fed beef is much leaner so there is little to insulate it from the heat source, making it important to cook with lower temperatures. Also because of the lack of insulation, the meat will cook about 30-50% faster! ",
    rating: 5,
    reviews: 19,
    availablity: "In Stock",
    img: "https://i.ibb.co/fFmLt3y/images-10.jpg",
  },
  {
    title: "Coarse flour",
    price: 40,
    id: 114,
    category: "Popular",
    description:
      "Whether you're already consuming sustainable meats like grass-fed beef, or you're heading in that direction, it's important to understand that meat raised on grass cannot always be prepared in the same way as conventional meat. Grass-fed beef is much leaner so there is little to insulate it from the heat source, making it important to cook with lower temperatures. Also because of the lack of insulation, the meat will cook about 30-50% faster! ",
    rating: 5,
    reviews: 23,
    availablity: "In Stock",
    img: "https://i.ibb.co/ckqTFDD/images-11.jpg",
  },
  {
    title: "Yellow",
    price: 45,
    id: 115,
    category: "Popular",
    description:
      "Whether you're already consuming sustainable meats like grass-fed beef, or you're heading in that direction, it's important to understand that meat raised on grass cannot always be prepared in the same way as conventional meat. Grass-fed beef is much leaner so there is little to insulate it from the heat source, making it important to cook with lower temperatures. Also because of the lack of insulation, the meat will cook about 30-50% faster! ",
    rating: 4,
    reviews: 21,
    availablity: "In Stock",
    img: "https://i.ibb.co/T14zvN1/images-12.jpg",
  },
  {
    title: "Hair Oil",
    price: 50,
    id: 116,
    category: "Popular",
    description:
      "Whether you're already consuming sustainable meats like grass-fed beef, or you're heading in that direction, it's important to understand that meat raised on grass cannot always be prepared in the same way as conventional meat. Grass-fed beef is much leaner so there is little to insulate it from the heat source, making it important to cook with lower temperatures. Also because of the lack of insulation, the meat will cook about 30-50% faster! ",
    rating: 5,
    reviews: 24,
    availablity: "In Stock",
    img: "https://i.ibb.co/4fV22TB/images-13.jpg",
  },
  {
    title: "Lentils",
    price: 35,
    id: 117,
    category: "Popular",
    description:
      "Whether you're already consuming sustainable meats like grass-fed beef, or you're heading in that direction, it's important to understand that meat raised on grass cannot always be prepared in the same way as conventional meat. Grass-fed beef is much leaner so there is little to insulate it from the heat source, making it important to cook with lower temperatures. Also because of the lack of insulation, the meat will cook about 30-50% faster! ",
    rating: 5,
    reviews: 26,
    availablity: "In Stock",
    img: "https://i.ibb.co/wCmZjcc/images-3.jpg",
  },
  {
    title: "Garlic",
    price: 30,
    id: 118,
    category: "Popular",
    description:
      "Whether you're already consuming sustainable meats like grass-fed beef, or you're heading in that direction, it's important to understand that meat raised on grass cannot always be prepared in the same way as conventional meat. Grass-fed beef is much leaner so there is little to insulate it from the heat source, making it important to cook with lower temperatures. Also because of the lack of insulation, the meat will cook about 30-50% faster! ",
    rating: 4,
    reviews: 16,
    availablity: "In Stock",
    img: "https://i.ibb.co/RvtWK5p/images-5.jpg",
  },
  {
    title: "Mango Trimming",
    price: 60,
    id: 120,
    category: "Popular",
    description:
      "Whether you're already consuming sustainable meats like grass-fed beef, or you're heading in that direction, it's important to understand that meat raised on grass cannot always be prepared in the same way as conventional meat. Grass-fed beef is much leaner so there is little to insulate it from the heat source, making it important to cook with lower temperatures. Also because of the lack of insulation, the meat will cook about 30-50% faster! ",
    rating: 5,
    reviews: 21,
    availablity: "In Stock",
    img: "https://i.ibb.co/MnyfQBZ/images-6.jpg",
  },
  {
    title: "Mango",
    price: 60,
    id: 120,
    category: "Popular",
    description:
      "Whether you're already consuming sustainable meats like grass-fed beef, or you're heading in that direction, it's important to understand that meat raised on grass cannot always be prepared in the same way as conventional meat. Grass-fed beef is much leaner so there is little to insulate it from the heat source, making it important to cook with lower temperatures. Also because of the lack of insulation, the meat will cook about 30-50% faster! ",
    rating: 5,
    reviews: 21,
    availablity: "In Stock",
    img: "https://i.ibb.co/LCmFyXJ/images-7.jpg",
  },
  {
    title: "Papaya",
    price: 40,
    id: 121,
    category: "Popular",
    description:
      "Whether you're already consuming sustainable meats like grass-fed beef, or you're heading in that direction, it's important to understand that meat raised on grass cannot always be prepared in the same way as conventional meat. Grass-fed beef is much leaner so there is little to insulate it from the heat source, making it important to cook with lower temperatures. Also because of the lack of insulation, the meat will cook about 30-50% faster! ",
    rating: 5,
    reviews: 23,
    availablity: "In Stock",
    img: "https://i.ibb.co/Rzj0sjH/images-8.jpg",
  },
  {
    title: "Tissue",
    price: 20,
    id: 122,
    category: "Popular",
    description:
      "Whether you're already consuming sustainable meats like grass-fed beef, or you're heading in that direction, it's important to understand that meat raised on grass cannot always be prepared in the same way as conventional meat. Grass-fed beef is much leaner so there is little to insulate it from the heat source, making it important to cook with lower temperatures. Also because of the lack of insulation, the meat will cook about 30-50% faster! ",
    rating: 5,
    reviews: 20,
    availablity: "In Stock",
    img: "https://i.ibb.co/5hfjGFm/images-9.jpg",
  },
];