const a = [
  {
    title: "Hen",
    price: 30,
    id: 1,
    category: "Eggs",
    description:
      "Whether you're already consuming sustainable meats like grass-fed beef, or you're heading in that direction, it's important to understand that meat raised on grass cannot always be prepared in the same way as conventional meat. Grass-fed beef is much leaner so there is little to insulate it from the heat source, making it important to cook with lower temperatures. Also because of the lack of insulation, the meat will cook about 30-50% faster! ",
    rating: 4,
    reviews: 25,
    availablity: "In Stock",
    img: "https://ibb.co/kBtVQKY",
  },
  {
    title: "Duck",
    price: 30,
    id: 163,
    category: "Eggs",
    description:
      "Whether you're already consuming sustainable meats like grass-fed beef, or you're heading in that direction, it's important to understand that meat raised on grass cannot always be prepared in the same way as conventional meat. Grass-fed beef is much leaner so there is little to insulate it from the heat source, making it important to cook with lower temperatures. Also because of the lack of insulation, the meat will cook about 30-50% faster! ",
    rating: 4,
    reviews: 25,
    availablity: "In Stock",
    img: "https://ibb.co/HHMhWXd",
  },
  {
    title: "Coyle",
    price: 30,
    id: 164,
    category: "Eggs",
    description:
      "Whether you're already consuming sustainable meats like grass-fed beef, or you're heading in that direction, it's important to understand that meat raised on grass cannot always be prepared in the same way as conventional meat. Grass-fed beef is much leaner so there is little to insulate it from the heat source, making it important to cook with lower temperatures. Also because of the lack of insulation, the meat will cook about 30-50% faster! ",
    rating: 4,
    reviews: 25,
    availablity: "In Stock",
    img: "https://i.ibb.co/WfDQt7W/Coyle.png",
  },
  {
    title: "Beef",
    price: 30,
    id: 165,
    category: "Meat",
    description:
      "Whether you're already consuming sustainable meats like grass-fed beef, or you're heading in that direction, it's important to understand that meat raised on grass cannot always be prepared in the same way as conventional meat. Grass-fed beef is much leaner so there is little to insulate it from the heat source, making it important to cook with lower temperatures. Also because of the lack of insulation, the meat will cook about 30-50% faster! ",
    rating: 4,
    reviews: 25,
    availablity: "In Stock",
    img: "https://i.ibb.co/CM1gnJn/Beef.jpg",
  },
  {
    title: "Chicken",
    price: 30,
    id: 265,
    category: "Meat",
    description:
      "Whether you're already consuming sustainable meats like grass-fed beef, or you're heading in that direction, it's important to understand that meat raised on grass cannot always be prepared in the same way as conventional meat. Grass-fed beef is much leaner so there is little to insulate it from the heat source, making it important to cook with lower temperatures. Also because of the lack of insulation, the meat will cook about 30-50% faster! ",
    rating: 4,
    reviews: 25,
    availablity: "In Stock",
    img: "https://i.ibb.co/tK9w8By/Hen-Egg.jpg",
  },
  {
    title: "Camel",
    price: 30,
    id: 166,
    category: "Meat",
    description:
      "Whether you're already consuming sustainable meats like grass-fed beef, or you're heading in that direction, it's important to understand that meat raised on grass cannot always be prepared in the same way as conventional meat. Grass-fed beef is much leaner so there is little to insulate it from the heat source, making it important to cook with lower temperatures. Also because of the lack of insulation, the meat will cook about 30-50% faster! ",
    rating: 4,
    reviews: 25,
    availablity: "In Stock",
    img: "https://i.ibb.co/rkZn8SZ/camel.jpg",
  },
  {
    title: "Mutton",
    price: 30,
    id: 167,
    category: "Meat",
    description:
      "Whether you're already consuming sustainable meats like grass-fed beef, or you're heading in that direction, it's important to understand that meat raised on grass cannot always be prepared in the same way as conventional meat. Grass-fed beef is much leaner so there is little to insulate it from the heat source, making it important to cook with lower temperatures. Also because of the lack of insulation, the meat will cook about 30-50% faster! ",
    rating: 4,
    reviews: 25,
    availablity: "In Stock",
    img: "https://i.ibb.co/Yjs0xxR/Mutton.jpg",
  },
  {
    title: "Buffalo",
    price: 30,
    id: 168,
    category: "Meat",
    description:
      "Whether you're already consuming sustainable meats like grass-fed beef, or you're heading in that direction, it's important to understand that meat raised on grass cannot always be prepared in the same way as conventional meat. Grass-fed beef is much leaner so there is little to insulate it from the heat source, making it important to cook with lower temperatures. Also because of the lack of insulation, the meat will cook about 30-50% faster! ",
    rating: 4,
    reviews: 25,
    availablity: "In Stock",
    img: "https://i.ibb.co/9pnQmFt/Buffalo.jpg",
  },
  {
    title: "Duck",
    price: 30,
    id: 169,
    category: "Meat",
    description:
      "Whether you're already consuming sustainable meats like grass-fed beef, or you're heading in that direction, it's important to understand that meat raised on grass cannot always be prepared in the same way as conventional meat. Grass-fed beef is much leaner so there is little to insulate it from the heat source, making it important to cook with lower temperatures. Also because of the lack of insulation, the meat will cook about 30-50% faster! ",
    rating: 4,
    reviews: 25,
    availablity: "In Stock",
    img: "https://i.ibb.co/chF9yB4/Duck.jpg",
  },
  {
    title: "Collard",
    price: 30,
    id: 170,
    category: "Vegetables",
    description:
      "Whether you're already consuming sustainable meats like grass-fed beef, or you're heading in that direction, it's important to understand that meat raised on grass cannot always be prepared in the same way as conventional meat. Grass-fed beef is much leaner so there is little to insulate it from the heat source, making it important to cook with lower temperatures. Also because of the lack of insulation, the meat will cook about 30-50% faster! ",
    rating: 4,
    reviews: 25,
    availablity: "In Stock",
    img: "https://i.ibb.co/SVFxYTw/Collard.jpg",
  },
  {
    title: "Corn",
    price: 30,
    id: 181,
    category: "Vegetables",
    description:
      "Whether you're already consuming sustainable meats like grass-fed beef, or you're heading in that direction, it's important to understand that meat raised on grass cannot always be prepared in the same way as conventional meat. Grass-fed beef is much leaner so there is little to insulate it from the heat source, making it important to cook with lower temperatures. Also because of the lack of insulation, the meat will cook about 30-50% faster! ",
    rating: 4,
    reviews: 25,
    availablity: "In Stock",
    img: "https://i.ibb.co/NCZCQtN/Corn.jpg",
  },
  {
    title: "Eggplant",
    price: 30,
    id: 182,
    category: "Vegetables",
    description:
      "Whether you're already consuming sustainable meats like grass-fed beef, or you're heading in that direction, it's important to understand that meat raised on grass cannot always be prepared in the same way as conventional meat. Grass-fed beef is much leaner so there is little to insulate it from the heat source, making it important to cook with lower temperatures. Also because of the lack of insulation, the meat will cook about 30-50% faster! ",
    rating: 4,
    reviews: 25,
    availablity: "In Stock",
    img: "https://i.ibb.co/fG0tN9B/Eggplant.jpg",
  },
  {
    title: "Pumpkin",
    price: 30,
    id: 183,
    category: "Vegetables",
    description:
      "Whether you're already consuming sustainable meats like grass-fed beef, or you're heading in that direction, it's important to understand that meat raised on grass cannot always be prepared in the same way as conventional meat. Grass-fed beef is much leaner so there is little to insulate it from the heat source, making it important to cook with lower temperatures. Also because of the lack of insulation, the meat will cook about 30-50% faster! ",
    rating: 4,
    reviews: 25,
    availablity: "In Stock",
    img: "https://i.ibb.co/tBfbkTq/Pumpkin.jpg",
  },
  {
    title: "Broccoli",
    price: 30,
    id: 184,
    category: "Vegetables",
    description:
      "Whether you're already consuming sustainable meats like grass-fed beef, or you're heading in that direction, it's important to understand that meat raised on grass cannot always be prepared in the same way as conventional meat. Grass-fed beef is much leaner so there is little to insulate it from the heat source, making it important to cook with lower temperatures. Also because of the lack of insulation, the meat will cook about 30-50% faster! ",
    rating: 4,
    reviews: 25,
    availablity: "In Stock",
    img: "https://i.ibb.co/s65rc8M/Images-of-food-Fresh-produce-A-head-of-broccoli-Brassicae-plant-Green-vegetable-Florets-in-tight-clu.jpg",
  },
  {
    title: "Carrot",
    price: 30,
    id: 185,
    category: "Vegetables",
    description:
      "Whether you're already consuming sustainable meats like grass-fed beef, or you're heading in that direction, it's important to understand that meat raised on grass cannot always be prepared in the same way as conventional meat. Grass-fed beef is much leaner so there is little to insulate it from the heat source, making it important to cook with lower temperatures. Also because of the lack of insulation, the meat will cook about 30-50% faster! ",
    rating: 4,
    reviews: 25,
    availablity: "In Stock",
    img: "https://i.ibb.co/ykZVf7W/Carrot.jpg",
  },
  {
    title: "Tomato",
    price: 30,
    id: 187,
    category: "Vegetables",
    description:
      "Whether you're already consuming sustainable meats like grass-fed beef, or you're heading in that direction, it's important to understand that meat raised on grass cannot always be prepared in the same way as conventional meat. Grass-fed beef is much leaner so there is little to insulate it from the heat source, making it important to cook with lower temperatures. Also because of the lack of insulation, the meat will cook about 30-50% faster! ",
    rating: 4,
    reviews: 25,
    availablity: "In Stock",
    img: "https://i.ibb.co/0V2j5dC/Potato.jpg",
  },
  {
    title: "Ginger",
    price: 30,
    id: 188,
    category: "Vegetables",
    description:
      "Whether you're already consuming sustainable meats like grass-fed beef, or you're heading in that direction, it's important to understand that meat raised on grass cannot always be prepared in the same way as conventional meat. Grass-fed beef is much leaner so there is little to insulate it from the heat source, making it important to cook with lower temperatures. Also because of the lack of insulation, the meat will cook about 30-50% faster! ",
    rating: 4,
    reviews: 25,
    availablity: "In Stock",
    img: "https://i.ibb.co/Y2Wyjvb/Ginger.jpg",
  },
  {
    title: "Cod",
    price: 30,
    id: 179,
    category: "Sea Foods",
    description:
      "Whether you're already consuming sustainable meats like grass-fed beef, or you're heading in that direction, it's important to understand that meat raised on grass cannot always be prepared in the same way as conventional meat. Grass-fed beef is much leaner so there is little to insulate it from the heat source, making it important to cook with lower temperatures. Also because of the lack of insulation, the meat will cook about 30-50% faster! ",
    rating: 4,
    reviews: 25,
    availablity: "In Stock",
    img: "https://i.ibb.co/NVLcpkz/Cod.jpg",
  },
  {
    title: "Salmon",
    price: 30,
    id: 180,
    category: "Sea Foods",
    description:
      "Whether you're already consuming sustainable meats like grass-fed beef, or you're heading in that direction, it's important to understand that meat raised on grass cannot always be prepared in the same way as conventional meat. Grass-fed beef is much leaner so there is little to insulate it from the heat source, making it important to cook with lower temperatures. Also because of the lack of insulation, the meat will cook about 30-50% faster! ",
    rating: 4,
    reviews: 25,
    availablity: "In Stock",
    img: "https://i.ibb.co/zSszfhr/Atlantic-Salmon-Salmo-solar-whole-isolated-on-a-white-studio-background.jpg",
  },
  {
    title: "Trout",
    price: 30,
    id: 181,
    category: "Sea Foods",
    description:
      "Whether you're already consuming sustainable meats like grass-fed beef, or you're heading in that direction, it's important to understand that meat raised on grass cannot always be prepared in the same way as conventional meat. Grass-fed beef is much leaner so there is little to insulate it from the heat source, making it important to cook with lower temperatures. Also because of the lack of insulation, the meat will cook about 30-50% faster! ",
    rating: 4,
    reviews: 25,
    availablity: "In Stock",
    img: "https://i.ibb.co/XVQbbDX/Trout.jpg",
  },
  {
    title: "Tuna",
    price: 30,
    id: 182,
    category: "Sea Foods",
    description:
      "Whether you're already consuming sustainable meats like grass-fed beef, or you're heading in that direction, it's important to understand that meat raised on grass cannot always be prepared in the same way as conventional meat. Grass-fed beef is much leaner so there is little to insulate it from the heat source, making it important to cook with lower temperatures. Also because of the lack of insulation, the meat will cook about 30-50% faster! ",
    rating: 4,
    reviews: 25,
    availablity: "In Stock",
    img: "https://i.ibb.co/6B8BKdb/Tuna.jpg",
  },
  {
    title: "Haddock",
    price: 30,
    id: 183,
    category: "Sea Foods",
    description:
      "Whether you're already consuming sustainable meats like grass-fed beef, or you're heading in that direction, it's important to understand that meat raised on grass cannot always be prepared in the same way as conventional meat. Grass-fed beef is much leaner so there is little to insulate it from the heat source, making it important to cook with lower temperatures. Also because of the lack of insulation, the meat will cook about 30-50% faster! ",
    rating: 4,
    reviews: 25,
    availablity: "In Stock",
    img: "https://i.ibb.co/xG7sdbW/Haddock.jpg",
  },
  {
    title: "Plaice",
    price: 30,
    id: 184,
    category: "Sea Foods",
    description:
      "Whether you're already consuming sustainable meats like grass-fed beef, or you're heading in that direction, it's important to understand that meat raised on grass cannot always be prepared in the same way as conventional meat. Grass-fed beef is much leaner so there is little to insulate it from the heat source, making it important to cook with lower temperatures. Also because of the lack of insulation, the meat will cook about 30-50% faster! ",
    rating: 4,
    reviews: 25,
    availablity: "In Stock",
    img: "https://i.ibb.co/0Jfp68k/Plaice.jpg",
  },
  {
    title: "Yogurt",
    price: 30,
    id: 185,
    category: "Sea Foods",
    description:
      "Whether you're already consuming sustainable meats like grass-fed beef, or you're heading in that direction, it's important to understand that meat raised on grass cannot always be prepared in the same way as conventional meat. Grass-fed beef is much leaner so there is little to insulate it from the heat source, making it important to cook with lower temperatures. Also because of the lack of insulation, the meat will cook about 30-50% faster! ",
    rating: 4,
    reviews: 25,
    availablity: "In Stock",
    img: "https://i.ibb.co/r6mFcX7/Yogurt.png",
  },
  {
    title: "Ice cream",
    price: 30,
    id: 186,
    category: "Dairy",
    description:
      "Whether you're already consuming sustainable meats like grass-fed beef, or you're heading in that direction, it's important to understand that meat raised on grass cannot always be prepared in the same way as conventional meat. Grass-fed beef is much leaner so there is little to insulate it from the heat source, making it important to cook with lower temperatures. Also because of the lack of insulation, the meat will cook about 30-50% faster! ",
    rating: 4,
    reviews: 25,
    availablity: "In Stock",
    img: "https://i.ibb.co/sF1DDFT/Ice-cream.jpg",
  },
  {
    title: "Fermented",
    price: 30,
    id: 187,
    category: "Dairy",
    description:
      "Whether you're already consuming sustainable meats like grass-fed beef, or you're heading in that direction, it's important to understand that meat raised on grass cannot always be prepared in the same way as conventional meat. Grass-fed beef is much leaner so there is little to insulate it from the heat source, making it important to cook with lower temperatures. Also because of the lack of insulation, the meat will cook about 30-50% faster! ",
    rating: 4,
    reviews: 25,
    availablity: "In Stock",
    img: "https://i.ibb.co/brjv3jb/Fermented.jpg",
  },
  {
    title: "Cheese",
    price: 30,
    id: 188,
    category: "Dairy",
    description:
      "Whether you're already consuming sustainable meats like grass-fed beef, or you're heading in that direction, it's important to understand that meat raised on grass cannot always be prepared in the same way as conventional meat. Grass-fed beef is much leaner so there is little to insulate it from the heat source, making it important to cook with lower temperatures. Also because of the lack of insulation, the meat will cook about 30-50% faster! ",
    rating: 4,
    reviews: 25,
    availablity: "In Stock",
    img: "https://i.ibb.co/vxCYsXm/Cheese.jpg",
  },
  {
    title: "Butter",
    price: 30,
    id: 189,
    category: "Dairy",
    description:
      "Whether you're already consuming sustainable meats like grass-fed beef, or you're heading in that direction, it's important to understand that meat raised on grass cannot always be prepared in the same way as conventional meat. Grass-fed beef is much leaner so there is little to insulate it from the heat source, making it important to cook with lower temperatures. Also because of the lack of insulation, the meat will cook about 30-50% faster! ",
    rating: 4,
    reviews: 25,
    availablity: "In Stock",
    img: "https://i.ibb.co/sQBRywp/Butter.jpg",
  },
  {
    title: "Cream",
    price: 30,
    id: 190,
    category: "Dairy",
    description:
      "Whether you're already consuming sustainable meats like grass-fed beef, or you're heading in that direction, it's important to understand that meat raised on grass cannot always be prepared in the same way as conventional meat. Grass-fed beef is much leaner so there is little to insulate it from the heat source, making it important to cook with lower temperatures. Also because of the lack of insulation, the meat will cook about 30-50% faster! ",
    rating: 4,
    reviews: 25,
    availablity: "In Stock",
    img: "https://i.ibb.co/ZdZkM9b/Cream.jpg",
  },
  {
    title: "Custard",
    price: 30,
    id: 191,
    category: "Dairy",
    description:
      "Whether you're already consuming sustainable meats like grass-fed beef, or you're heading in that direction, it's important to understand that meat raised on grass cannot always be prepared in the same way as conventional meat. Grass-fed beef is much leaner so there is little to insulate it from the heat source, making it important to cook with lower temperatures. Also because of the lack of insulation, the meat will cook about 30-50% faster! ",
    rating: 4,
    reviews: 25,
    availablity: "In Stock",
    img: "https://i.ibb.co/YpgmGgs/Custard.jpg",
  },
  {
    title: "Almonds",
    price: 30,
    id: 192,
    category: "Nuts and seeds",
    description:
      "Whether you're already consuming sustainable meats like grass-fed beef, or you're heading in that direction, it's important to understand that meat raised on grass cannot always be prepared in the same way as conventional meat. Grass-fed beef is much leaner so there is little to insulate it from the heat source, making it important to cook with lower temperatures. Also because of the lack of insulation, the meat will cook about 30-50% faster! ",
    rating: 4,
    reviews: 25,
    availablity: "In Stock",
    img: "https://i.ibb.co/sgLtJx1/Almonds.jpg",
  },
  {
    title: "Pecans",
    price: 30,
    id: 1193,
    category: "Nuts and seeds",
    description:
      "Whether you're already consuming sustainable meats like grass-fed beef, or you're heading in that direction, it's important to understand that meat raised on grass cannot always be prepared in the same way as conventional meat. Grass-fed beef is much leaner so there is little to insulate it from the heat source, making it important to cook with lower temperatures. Also because of the lack of insulation, the meat will cook about 30-50% faster! ",
    rating: 4,
    reviews: 25,
    availablity: "In Stock",
    img: "https://i.ibb.co/fQfZ7dd/Pecans.webp",
  },
  {
    title: "Pistachios",
    price: 30,
    id: 196,
    category: "Nuts and seeds",
    description:
      "Whether you're already consuming sustainable meats like grass-fed beef, or you're heading in that direction, it's important to understand that meat raised on grass cannot always be prepared in the same way as conventional meat. Grass-fed beef is much leaner so there is little to insulate it from the heat source, making it important to cook with lower temperatures. Also because of the lack of insulation, the meat will cook about 30-50% faster! ",
    rating: 4,
    reviews: 25,
    availablity: "In Stock",
    img: "https://i.ibb.co/xFc10fJ/Pistachios.jpg",
  },
  {
    title: "Pumpkin Seeds",
    price: 30,
    id: 195,
    category: "Nuts and seeds",
    description:
      "Whether you're already consuming sustainable meats like grass-fed beef, or you're heading in that direction, it's important to understand that meat raised on grass cannot always be prepared in the same way as conventional meat. Grass-fed beef is much leaner so there is little to insulate it from the heat source, making it important to cook with lower temperatures. Also because of the lack of insulation, the meat will cook about 30-50% faster! ",
    rating: 4,
    reviews: 25,
    availablity: "In Stock",
    img: "https://i.ibb.co/QfhRYY6/Pumpkin-Seeds.jpg",
  },
  {
    title: "Macadamias",
    price: 30,
    id: 194,
    category: "Nuts and seeds",
    description:
      "Whether you're already consuming sustainable meats like grass-fed beef, or you're heading in that direction, it's important to understand that meat raised on grass cannot always be prepared in the same way as conventional meat. Grass-fed beef is much leaner so there is little to insulate it from the heat source, making it important to cook with lower temperatures. Also because of the lack of insulation, the meat will cook about 30-50% faster! ",
    rating: 4,
    reviews: 25,
    availablity: "In Stock",
    img: "https://i.ibb.co/QK9vXSj/Macadamias.jpg",
  },
  {
    title: "Chicken (Poultry)",
    price: 30,
    id: 1036,
    category: "Meat",
    description:
      "Whether you're already consuming sustainable meats like grass-fed beef, or you're heading in that direction, it's important to understand that meat raised on grass cannot always be prepared in the same way as conventional meat. Grass-fed beef is much leaner so there is little to insulate it from the heat source, making it important to cook with lower temperatures. Also because of the lack of insulation, the meat will cook about 30-50% faster! ",
    rating: 4,
    reviews: 25,
    availablity: "In Stock",
    img: "https://i.ibb.co/jyhnpGY/Chicken-poultry.jpg",
  },
];
